name: gym_finance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  sqflite: ^2.2.0
  path: ^1.8.3
  firebase_core: ^3.13.0
  cloud_firestore: 5.6.6
  firebase_auth: ^5.5.2
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
